### ISSUE TITLE
declaring arc4random_buf arc4random arc4random_stir arc4random_uniform

### ISSUE THREAD

**Issue by Safari77** [libressl-portable/portable#109]
These functions are not declared in the installed headers. 

When compiling openssh-portable on Linux:
```
sshd.c:397:2: warning: implicit declaration of function ‘arc4random_buf’ [-Wimplicit-function-declaration]
```
because AC_CHECK_FUNCS does not care about implicit declaration..

**Comment by bcook-r7** [comment]
I don't think we intend to declare arc4random_buf as a library function in the headers from LibreSSL. It is a compatibility function added to work around this function being missing from the Linux C library. We still need to export the symbol though, since it is used in libcrypto, libssl, libtls, openssl(1), etc. but these use LibreSSL's internal shim headers.

Alternative solutions would be for your C library to support arc4random, or openssh-portable could include the definition in its own compat headers if it is not found in stdlib.h.

**Comment by busterb** [comment]
I think this should probably be redirected toward the openssh-portable project. The problem is that the configure script is not checking if the system headers are defining these files, which is certainly doable. See the recent discussion about this here #120

**Comment by busterb** [comment]
I was unable to find the corresponding bug in the openssh portable bug tracker, so I made one. Thanks for the report:

https://bugzilla.mindrot.org/show_bug.cgi?id=2465
