### ISSUE TITLE
RSAX and other engines

### ISSUE THREAD

**Issue by hdatma** [libressl-portable/portable#119]
> * Removed RSAX engine
> * --with-enginesdir is removed as a configuration parameter

http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.2.2-relnotes.txt

Both the source code and google leave us without additional information. 

Would anyone in authority please fill the gap of knowledge and describe 
the facts, the reasoning on those facts, and the conclusions that
led to this otherwise arbitrary, dogmatic and occlusive decision?

**Comment by busterb** [comment]
Hi @hdatma 

--with-enginesdir has been a no-op since at least 2.2.1, when we removed the dynamic engine loader. The dynamic engine loader, while it can allow things like proprietary accelerators or other 3rd party modules to hook into the crypto code path, also presents a security risk if an one can cause the loading of a library from a attacker-controlled location. The standard OpenSSL dynamic engines themselves have never been built in LibreSSL since the very first release (so enginesdir has always been empty by default). We're further working to reduce the footprint of other engine code, which has already been removed entirely in BoringSSL.

RSAX itself has been removed from OpenSSL's master branch for a couple of years already - this is the actual patch that removed it from LibreSSL: https://github.com/libressl-portable/openbsd/commit/5e36728d2ce6c1544fdfcd6835683eccd9a2dacb

The RSAX code did not have very robust error handling, calling exit(1) in failure paths. It may also be vulnerable to side-channel analysis, at least based on reading about its replacement, RSAZ (http://rt.openssl.org/Ticket/Display.html?id=2850, http://rt.openssl.org/Ticket/Display.html?id=2582). It also only works with 1024 bit keys on x86_64 which, though understandably may be important in your environment, are being phased out: https://blog.mozilla.org/security/2014/09/08/phasing-out-certificates-with-1024-bit-rsa-keys/

If you need the performance that RSAX provided in your environment, we should perhaps look at integrating RSAZ, which performs better, improves side channel resistance, and works on 2048 bit keys. If you need something like dynamic engine support in your environment, we have discussed creating a privilege-separation mechanism that does not require loading external code into the same memory space, though I am not sure if there is concrete work there yet.

There was a similar discussion the GOST engine support when it was missed in LibreSSL. In response, contributor Dmitry Eremin-Solenikov converted GOST algorithms to work as a standard crypto algorithms in libcrypto, which we merged last year.

Thanks, I'd be happy to hear more about your use-cases.

**Comment by hdatma** [comment]
Hi @busterb 

I do everything with a handful of ciphersuites:  0xcc13, 0xc030, 0xc02f, 0xc028 and 0xc014. 
It is the removal of support for hardware acceleration that bothers me, not RSAX in particular. The software I am developing relies heavily on TLS (so much that each new version of the library compels me to recompile the whole thing, resulting in 1.3 GB of data), and I need the TLS engine to be as fast as possible on common Intel-based hardware with AES-NI, to avoid taxing the rest of the CPU. 

Thank you, very much, for the explanation.

**Comment by busterb** [comment]
It is worth noting that these changes do not preclude hardware acceleration
at all, rather the way it is implemented should not use the deprecated
'engine' mechanism. AES-NI instructions are still enabled with Libressl
2.2.2. It is possible to improve RSA operations in a similar way without
the user needing to load or initialize extra 'engine' code.

**Comment by hdatma** [comment]
2 x thank you

**Comment by hdatma** [comment]
Version 2.2.2 breaks unbound (dnssec resolver).

**Comment by busterb** [comment]
In what way? Unbound is part of the OpenBSD base system, and it passes all tests. 

Are we still discussing the old RSAX engine? If not, please open a new issue and we can close this one.

**Comment by hdatma** [comment]
No, no, we are no longer discussing the old engines. Will open a new issue for it.
