### ISSUE TITLE
soname bumps require me to recompile all apps linked against -lssl

### ISSUE THREAD

**Issue by rofl0r** [libressl-portable/portable#126]
on each upgrade of libressl i get messages like
```
Error relocating /bin/wpa_supplicant: EVP_CipherUpdate: symbol not found
Error relocating /bin/wpa_supplicant: SSL_set_bio: symbol not found
```
```
Error loading shared library libssl.so.32: No such file or directory (needed by /bin/wpa_supplicant)
```
rather than libssl.so, the soname used gets hardcoded into the DT_NEEDED section of binaries linking against -lssl
```
$ readelf -a /lib/libssl.so | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libssl.so.35]
```
imo, it should be possible to reuse existing binaries when bumping the libressl version (as is the case when using upstream openssl).

**Comment by bob-beck** [comment]
We bump that version number when there are ABI changes that required it. So for example, it does not change from LibreSSL 2.2.2 to 2.2.3.  It will change if there are ABI changes that would potentially make your program do something horribly wrong if you don't relink. 

If you want to keep your old binaries, keep the old shared library around.. That's really the way this
needs to happen for safety.  (So for example, this should be possible with 2.2.2 -> 2.2.3 - because it's safe there).

**Comment by Qix-** [comment]
Just out of curiosity, do you use a versioning system that reflects this, @bob-beck? Something like [semver](http://semver.org/)?

**Comment by 4a6f656c** [comment]
Somewhat. The short version is that if an API addition is made, then the minor is bumped and if a API removal or change/break is made, the major is bumped.

**Comment by Sp1l** [comment]
Check for versions in http://www.libressl.org/releases.html that are part of an OpenBSD release. These will keep the same shlib versions and only get errata and security fixes.
