### ISSUE TITLE
Add make install_sw support

### ISSUE THREAD

**Issue by Commenter123** [libressl-portable/portable#174]
Yesterday nginx 1.9.12 was released.
In this commit they changed the make install command of custom openssl to `make install_sw`: 
https://github.com/nginx/nginx/commit/fef872a9ba628a105504b6ef4653cfd1560f8e79
This breaks compatibility with libressl.

Also see this bugreport which nginx guys closed: "wontfix"
https://trac.nginx.org/nginx/ticket/908

**Comment by hdatma** [comment]
It is good to save time by skipping the compilation of unwanted manuals.

Perhaps a quick fix is to regex  auto/lib/openssl/make of nginx, to force it
into the old behaviour of compiling everything?

**Comment by busterb** [comment]
We already met nginx half-way with the 'config' script. It should be possible to add another phony target to Makefile.am to simulate install_sw. Given that it takes all of 5 seconds to do a full install with libressl (since it doesn't have to compile any .pod files), i'm not sure the extra effort to avoid manpages is worth it.

Try this patch:

```
diff --git a/Makefile.am b/Makefile.am
index 0804984..d92f347 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -6,3 +6,6 @@ pkgconfig_DATA = libcrypto.pc libssl.pc libtls.pc openssl.pc

 EXTRA_DIST = README.md README.windows VERSION config scripts
 EXTRA_DIST += CMakeLists.txt
+
+.PHONY: install_sw
+install_sw: install
```

**Comment by bob-beck** [comment]
I am in full agreement with this approach :)

**Comment by Commenter123** [comment]
Works fine. Please add this into master

**Comment by Angristan** [comment]
Any update ?

**Comment by busterb** [comment]
sure, fix is coming soon

**Comment by Angristan** [comment]
Thanks :D
