### ISSUE TITLE
detect all protocols disabled and error nicely instead of failing late

### ISSUE THREAD

**Issue by mimaen** [libressl-portable/portable#186]
s_client incorporates these switches to select protocol:

```
-no_tls1_2/-no_tls1_1/-no_tls1/-no_ssl3/-no_ssl2 - turn off that protocol
-tls1_2/-tls1_1/-tls1 - just use that protocol
```

I'm trying to connect to server directly with SSLv3, so I use:

`openssl s_client -bugs -msg -no_tls1_2 -no_tls1_1 -no_tls1 -connect server.example.com:443`

LibreSSL 2.3.2 starts handshake with a TLS 1.2 ClientHello, causing a handshake failure with this particular server.

OpenSSL 1.0.1f with identical syntax starts handshake with a SSL 3.0 ClientHello, which is the only way to connect to that server.

Is there any way to force SSL3 (and SSL2) handshake?

**Comment by bob-beck** [comment]
no. the ssl3 code has been deleted

if you want to use insecure protocols you will have to use something else.
 openssl still has the code

**Comment by mimaen** [comment]
to avoid confusion, it would be better to remove obsolete switches

`-no_ssl3/-no_ssl2`

and throw an error if the user disables all available protocols

`openssl s_client -no_tls1_2 -no_tls1_1 -no_tls1 -connect server.example.com:443`

**Comment by 4a6f656c** [comment]
The `-no_ssl3` and `-no_ssl2` flags still make sense to some extent. They disable ssl3/ssl2, which are both no-ops since they're already disabled. There are no longer `-ssl3` or `-ssl2` flags, since there is no way they can work.

Re disabling all available protocols, it would be nice if that produced an error, however libssl does not currently detect that all protocols are disabled until it is creating or decoding a ClientHello. This could be changed, however it is likely a low priority feature request.

**Comment by bob-beck** [comment]
I'm not too keen on removing no_ssl3 and no_ssl2 flags - this just breaks stuff needlessly

**Comment by 4a6f656c** [comment]
This is now fixed - we'll now fail with "no protocols available" before sending the client hello, rather than failing later with "unsupported protocol" when processing the server hello.
