### ISSUE TITLE
pet projects now broken under libressl

### ISSUE THREAD

**Issue by hdatma** [libressl-portable/portable#249]
Openssl is changing in ways that are breaking compatibility with libressl: as projects adapt to openssl, they stop working with libressl. Examples of broken projects: nmap-7.40, postfix-3.1.3, dovecot-2.2.27.

**Comment by 4a6f656c** [comment]
What exactly are you asking us to do here?

If these projects have migrated to OpenSSL 1.1 only, then they have effectively broken themselves on every known platform. If they still have compatibility code for OpenSSL 1.0 then they should work with LibreSSL (they may need slight changes to make the same code paths be used).

You can find patches to make most of these projects work with LibreSSL in both the OpenBSD ports tree (http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/ - for example, http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/mail/dovecot/patches/) and other places such as the Alpine Linux Aports tree (for example, http://git.alpinelinux.org/cgit/aports/tree/main/dovecot/libressl.patch).

Have you talked to any of these projects about supporting LibreSSL, or tried pushing patches to them?

Last but not least, most of these issues can be completely avoided by checking for function/symbol availability instead of using #if/#ifdef - as an example, hexchat did this recently - https://github.com/hexchat/hexchat/commit/d583ca7d922e5ac6ff466df2e4411b1303a3a2a3.

**Comment by hdatma** [comment]
> Have you talked to any of these projects about supporting LibreSSL, or tried pushing patches to them?

Yes.

**Comment by hdatma** [comment]
Re: http://git.alpinelinux.org/cgit/aports/tree/main/dovecot/libressl.patch

Your "patch" above causes horrible warnings when compiling, and crashes the tests. Do not use it.

**Comment by AliceWonderMiscreations** [comment]
Current dovecot requires more than just that or yes, you get problems.

[dovecot-2.2.27-libressl.patch.txt](https://github.com/libressl-portable/portable/files/679147/dovecot-2.2.27-libressl.patch.txt)

That builds and passes test in CentOS 7 building against LibreSSL unless valgrind is installed, where the tests fail - but Valgrind sometimes has false positives, not sure if that is the case here.

Dovecot built against LibreSSL with that patch however has been personally working for me without issue, but I make no guarantees.

**Comment by hdatma** [comment]
> Dovecot built against LibreSSL with that patch however has been personally working
> for me without issue, but I make no guarantees. 

This is the old patch for 2.2.26.0, which triggers panic errors in the tests for 2.2.27. Do not use it.

**Comment by hdatma** [comment]
Spot on and well worth reading: 

https://www.mail-archive.com/tech@openbsd.org/msg36437.html

**Comment by AliceWonderMiscreations** [comment]
That patch is a patch I created for 2.2.27 and if you would look at it you would see that it was made against 2.2.27 as it is in the very first lines.

It does not trigger panic errors during tests on my system. When I have valgrind installed then there are problems so there very likely are still some issues, but when valgrind isn't used, the tests complete and I have dovecot installed 2.2.27 installed on three different servers where it is working.

If you are experiencing test issues, please post what they are, as they likely can be fixed if it is known what they are.

**Comment by hdatma** [comment]
https://github.com/libressl-portable/portable/issues/252

**Comment by 4a6f656c** [comment]
>> What exactly are you asking us to do here?

> (Should I respond to this?) I do not recall asking for anything.

Yes, please - you've raised an issue against libressl-portable. Presumably that means that you want us to do something to address the issue. I'm asking what it is that you're suggesting we do.

>> Have you talked to any of these projects about supporting LibreSSL, or tried pushing patches to them?

> Yes.

And the result has been?

Regarding the patches, they were examples of what usually needs to be done in order to make software work with LibreSSL. I know the OpenBSD porters have a full set of patches for Dovecot 2.2.27 and I would be very surprised if these did not work.

**Comment by 4a6f656c** [comment]
Closing due to lack of response.

**Comment by hdatma** [comment]
> I know the OpenBSD porters have a full set of patches for Dovecot 2.2.27 and I would be very surprised if these did not work.

Did you read https://github.com/libressl-portable/portable/issues/252 ?
