### ISSUE TITLE
LibreSSL does not validate times not representable on the system (FreeBSD 32 bit has 32 bit time)

### ISSUE THREAD

**Issue by nakal** [libressl-portable/portable#251]
I have self-signed certificates to access my IMAP server. Applications linked on FreeBSD i386 with LibreSSL 2.4.4 reject connections.

I can reproduce it easily:
```
/usr/local/bin/openssl s_client -connect myhost:143 -starttls imap -CAfile cacert.pem
```

On amd64 LibreSSL succeeds with verify return code 0. On i386 it fails with verify error code 14 (format error in notAfter). OpenSSL works on both platforms.

**Comment by kinichiro** [comment]
Hi,

LibreSSL checks the size of time_t while building (configure or cmake)
for year 2038 issue, and shows warning if the size of time_t is 4.

```
** Warning, this system is unable to represent times past 2038
** It will behave incorrectly when handling valid RFC5280 dates
```

Don't you see that warning when you build LibreSSL on your FreeBSD/i386 ?
Or can you tell the size of time_t of your FreeBSD/i386 ?
And what value is set for 'notAfter' field in your self-signed certificates ?

Best regards,

**Comment by nakal** [comment]
You are right. The CA certificate expires in 2042. `time_t`  is just 4 bytes.

**Comment by nakal** [comment]
I don't know, if you want to close the issue, because I am not sure if you want to support systems with 32-bit `time_t`. It is obviously not a bug report, but request for a feature.

At the moment, it does not make sense for me to use LibreSSL on FreeBSD/i386. And your answer helped me to find out what is wrong on my system and I can resolve it on my own now. Thank you.

**Comment by bob-beck** [comment]
In short - supporting values with this time on a system with 32 bit time_t is
pretty much madness martin.  You are dealing with a certificate where anything
that displays it or moves it to a system time for comparison in an external 
library will almost certainly have issues.  This is why we complain and
check sizes of time_t at compile time, and refuse to validate things that
are not represntable by the system time..   

Your safest bet would be to make that certificate valid until Jan 1 2038, 
and pressure freebsd to get 64 bit time_t support on their 32 bit platforms, 
just as OpenBSD and a lot of other things already have, otherwise, you're kind
of playing with fire and an interesting attack surface for someone to start
sending you certificates (OCSP values, etc. etc.) for times that your system
can't represent and have "interesting" failure modes that will impact you

**Comment by bob-beck** [comment]
In short, we support systems with 32 bit time, but do not support the validation of times outside of the range representable by 32 bit time on said systems, because we believe that doing so is dangerous, and encourage people to use systems that have solved the 2038 problem for unix.
