### ISSUE TITLE
tls_handshake() raises error if handshake has already been done

### ISSUE THREAD

**Issue by vsajip** [libressl-portable/portable#272]
`tls_handshake()` sets the `TLS_HANDHAKE_COMPLETE` flag once the handshake is completed, and various things check it to initiate a handshake if one hasn't been done. This is helpful, but `tls_handshake()` doesn't check the flag itself, and, if called twice, it raises an "unknown alert" error because it tries to actually do the handshake again. It might be better if it checks the flag and, if set, returns success straight away.

**Comment by 4a6f656c** [comment]
If tls_handshake() is called on a context that has already completed a TLS handshake, it should return an error since this is likely a bug/issue with the calling code. That said, it should be an obvious error rather than it actually sending TLS packets that result in alerts. This has just been fixed in libtls.
