### ISSUE TITLE
getrandom(2) used in blocking mode

### ISSUE THREAD

**Issue by fabled** [libressl-portable/portable#274]
It is good to see getrandom(2) used for gathering entropy in linux. However, this blocks until the kernel's entropy pool is initialized. This can delay boot-up on 15-30 seconds depending on things. This is what we observed after switching from openssl to libressl. See e.g.:
- http://bugs.alpinelinux.org/issues/6329
- http://bugs.alpinelinux.org/issues/6635

Would make sense to call getrandom with the GRND_NONBLOCK flag set, and revert to the fallback code when entropy pool is not yet initialized? Or would be possible to set this based on if user is calling RAND_bytes vs. RAND_pseudo_bytes?

**Comment by 4a6f656c** [comment]
LibreSSL intentionally does not distinguish between RAND_bytes() and RAND_pseudo_bytes() - both are deliberately wrappers around arc4random().

The real issue here is that getrandom(2) blocks - on OpenBSD this is not an issue since getentropy(2) (which getrandom(2) is effectively based on) will not block and always succeeds. I suspect that the only two options are to either continue blocking when getrandom(2) blocks, or to use the fallback code in that situation as you suggest (although it is a pretty dismal situation when you have getrandom(2) but cannot use it...)

**Comment by busterb** [comment]
I think it is more useful to ask why it's blocking in the first place, and why OpenBSD, which has very similar semantics, is not. It looks to be in large part due to OpenBSD saving and restoring random seeds between restarts, which allows the random number generator to seed very early. Debian/Ubuntu seem to have this same setup, see /etc/init.d/urandom.

Why not solve this at a system level instead of application-level workarounds?

**Comment by busterb** [comment]
Correct me if I'm wrong @4a6f656c but woudn't OpenBSD technically block too if there was no entropy, but because it seeds even from the initial install, this not an issue in practice?

**Comment by bob-beck** [comment]
Well, or the real issue is that getrandom(2) blocks for 30 or 40 seconds..
  I'd love some more details on the sort of thing that this is blocking on.
(Is this a vm?)  Given that on https://lwn.net/Articles/572679/ I see that
urandom is normally ready before init even runs, this sounds like you may
have some sort of other issue that is
preventing your Linux kernel from having urandom initialized (so getrandom
is then guaranteed not to block for 256 bytes - as per
http://man7.org/linux/man-pages/man2/getrandom.2.html).  Fundamentally,
moving forward without this is probably not safe.

So the fundamental problem here is on OpenBSD a variety of mechanisms are
used to ensure that the system really doesn't come up multi-user without a
usable
pool of entropy for geentropy() (you can think of this in Linux terms that
"the urandom pool is initialized").  The same guarantees can't really be
made for Linux, or
at least according to http://man7.org/linux/man-pages/man2/getrandom.2.html
.

 Given that, lacking other information,  I'm very very reluctant to make
any official change to libressl to operate without sane returns from
getrandom(). In a nutshell, this is where machines are wholesale
compromised. if you are pausing 30 to 40 seconds on boot that's probably a
*very good thing* in this context, or, for example, your machine might come
up and generate predictable ssh keys - do you really want the compromise
where "hey look, all things based on alpine in the cloud have one of these
200,000 SSH keys".  So from that perspective, this "pause" is probably a
good thing, given the alternative. Effectively for me, that pause is Linux
saying "it is not safe to
proceed yet, please wait".  Frankly, to be honest with you, I use some
Linuxen in places (I'm not just an OpenBSD guy) and given what I see about
what is
going on there, if getrandom(2) actually blocks on boot, well, I wanna wait
for it.   Your alternative before this was *probably proceeding unsafely*
and that's kind of a
terrifying thought given that the first thing you're gonna do is start
generating host keys on first boot.

So at the moment, I'll leave this open, but I would initially consider this
a "Linux kernel in your configuration" problem. I'd happily discuss
figuring out why that's blocking for 30-40 seconds though, that sounds very
long. given the message I see above from Ted T'so about the topic. Perhaps
there is some configuration that is off.  Do you know if Linux can save
it's entropy state between boots (OpenBSD does this)

**Comment by bob-beck** [comment]
... and if it wasn't doing this sort of thing before, I'd be fascianted to
look at how alpine was booting up pre-LibreSSL and how predictable early
uses of entropy
for key generation were, if it was coming up before urandom was actually
initalized and just proceeding... Possibly very interesting }8->

**Comment by fabled** [comment]
I'm pretty sure the boot-up delay varies based on hardware and if virtualized or not. Openssl seems to access /dev/*random with O_NONBLOCK and with small timeout, so this issue was never there. I'm wondering if the processes that need random numbers are requiring really high-entropy or if they are good with c-library level random numbers. But I believe the openssl APIs for generating random numbers are not expected to block for long times, which can now happen in libressl when using getrandom().

**Comment by rfs613** [comment]
On a headless system, the delay seems to be infinite in some cases, not just 30 or 40 seconds. I have Alpine linux running on a ChromeBox as my home gateway. After upgrading from to Alpine 3.5 (which switched from openssl to libressl) my box hangs forever during boot. Only after plugging in a keyboard and monitor, and pressing a few keys, does it finish booting up.

**Comment by ncopa** [comment]
@rfs613 i wonder if you could test to add `jitterentropy_rng` to `/etc/modules` on your alpine 3.5 box and see if it helps?

**Comment by rfs613** [comment]
@ncopa no effect, boot still hangs until keyboard activity occurs. (I was able to manually modprobe the module, so it is present on my system, and I did not make a typo in /etc/modules).

**Comment by OldskoolOrion** [comment]
wow.. that long ? that's dma issue at startup time!

**Comment by bob-beck** [comment]
Further analysis of getrandom() has led us to conclude that it is as broken
as every previous attempt to solve this in Linux.  This could be rectified by ensuring
the kernel is initialized before init/systemd is started. 

have:https://github.com/openbsd/src/commit/edb2eeb7da8494998d0073f8aaeb8478cee5e00b
