### ISSUE TITLE
Problem if TLSv1 and TLSv1.2 are enabled without TLSv1.1

### ISSUE THREAD

**Issue by O2Graphics** [libressl-portable/portable#276]
Hello,

I've built nginx 1.11.9 with LibreSSL 2.5.1 on FreeBSD and now I have a bug.

My SSL configuration in nginx is:
`ssl_protocols TLSv1 TLSv1.2;`
and when doing that, Chromium and SSL Labs thinks there is only TLSv1 available.
If I configure with:
`ssl_protocols TLSv1 TLSv1.1 TLSv1.2;`
or:
`ssl_protocols TLSv1.2;`
the correct versions of the protocols are detected.

Previously I was using nginx 1.11.8 with LibreSSL 2.5.0 and it was working correctly without TLSv1.1.
I've also rebuilt nginx 1.11.9 with LibreSSL 2.5.0 and it also works correctly without TLSv1.1.

So it seems to be a regression in LibreSSL 2.5.1.

Best Regards.

**Comment by 4a6f656c** [comment]
I'll ponder this, but at this stage it is likely "working as intended"...

From the perspective of a TLS client supported TLS versions have to be contiguous, since there is no way to indicate support for specific versions (at least prior to TLSv1.3). Supporting non-contiguous versions on the server is possible, but has questionable value. As part of the recent code improvements, we've enforced contiguous ranges in both the client and the server, which also paves the way to support the SSL_set_min_proto_version() and SSL_set_max_proto_version() that are in BoringSSL and OpenSSL 1.1 (instead of the SSL_OP_NO_XYZ options that are used currently).

What's your reasoning for wanting to disable TLSv1.1 but keep TLSv1.0 enabled on the server side?

**Comment by O2Graphics** [comment]
Thanks for your answer.
I understand your reasons, I reported it because the behavior changed compared to previous versions of LibreSSL or OpenSSL.

I didn't understand immediatly what broke, because I also have HTTP/2 enabled on nginx and I couldn't reach my server anymore. Turned out the browser was trying a combination of TLSv1 with HTTP/2 which of course isn't supported.

My reasonning is: every browsers which understand TLSv1.1 also understand TLSv1.2, so it's useless to keep v1.1.
And I'm keeping TLSv1 for old browsers/OS (mainly IE8 on XP and Android < 4.4)

**Comment by AliceWonderMiscreations** [comment]
Yeah what I do is servers that need TLS 1.0 get 1.0, 1.1, 1.2 and servers that do not need 1.0 only get 1.2.

Currently I personally only keep TLS 1.0 around on some servers because there were some social media scrapers using crusty builds of curl that couldn't scrape content with TLS 1.2. And mail servers, some of them only do TLS 1.0 and that I suppose is better than SMTP via plain text.

**Comment by O2Graphics** [comment]
I agree, for mail server it's best to keep all versions of TLS.

**Comment by 4a6f656c** [comment]
I understand this was an unexpected change in behaviour.

If you disable TLSv1.1 on the server-side it will make no difference to clients that support TLSv1.2 or TLSv1.0. However, if there are clients that support TLSv1.1 (but not TLSv1.2), then you're forcing them to downgrade to TLSv1.0, which is likely worse then having TLSv1.1 enabled on the server.

**Comment by O2Graphics** [comment]
Yes, I know if a browser support TLSv1.1 and I only provide 1.0 and 1.2, it will downgrade to 1.0. 

Anyway if it's better for LibreSSL (better code, better security,…) to support only contiguous TLS version, I think you can close this issue.
