### ISSUE TITLE
ChaCha20-Poly1305 most preferred cipher suite

### ISSUE THREAD

**Issue by amirymk** [libressl-portable/portable#299]
How to modify a file ssl/s3_lib.c

So it works ChaCha20-Poly1305 most preferred cipher suite on libressl-2.5,1

ChaCha20-Poly1305-most-preferred-cipher-suite.patch

Because I tried but did not work with me.

Thanks

**Comment by 4a6f656c** [comment]
I'm not sure what ChaCha20-Poly1305-most-preferred-cipher-suite.patch is, or where you got it from...

LibreSSL uses ChaCha20-Poly1305 as the default, unless the host supports hardware accelerated AES, in which case it will prefer AES instead. If you really want to change the order, the easiest option is to explicitly specify the cipher list. Otherwise, if you want to change it at compile time you would need to modify ssl_create_cipher_list() in ssl_ciph.c (search for ssl_aes_is_accelerated).
