### ISSUE TITLE
crypto_portable.sym and out of tree build

### ISSUE THREAD

**Issue by graywolf** [libressl-portable/portable#300]
Hi,
is out of tree build officially supported by libressl? If yes, one file was overlooked:

	$ CC=i686-w64-mingw32-gcc CPPFLAGS=-D__MINGW_USE_VC2005_COMPAT ../libressl-2.5.2/configure --prefix=~/mingw/i686-w64-mingw32 --host=i686-w64-mingw32
	$ git status
	On branch master
	Untracked files:
	  (use "git add <file>..." to include in what will be committed)

		libressl-2.5.2/crypto/crypto_portable.sym

	nothing added to commit but untracked files present (use "git add" to track)

**Comment by busterb** [comment]
It should be included. Will fix, thanks!

On Apr 9, 2017, at 1:54 PM, W. <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
is out of tree build officially supported by libressl? If yes, one file was overlooked:

$ mkdir build
$ cd build
$ ../libressl-2.5.2/configure
$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        libressl-2.5.2/crypto/crypto_portable.sym

nothing added to commit but untracked files present (use "git add" to track)

**Comment by busterb** [comment]
Well, actually since this is a generated file, we should be generating it in builddir, so we don't have to write it into a source tree that may be write-only (right now we do a chmod and hope for the best). It seems $abs_top_builddir is not available in configure.ac's context, so testing with the internal $ac_abs_top_builddir instead.

**Comment by graywolf** [comment]
thank you :)

**Comment by graywolf** [comment]
Was the fix supposed to be in 2.5.3? If yes, it should be reopened since the issue still persist:

	$ git status
	On branch master
	Untracked files:
	  (use "git add <file>..." to include in what will be committed)

		libressl-2.5.3/crypto/crypto_portable.sym

**Comment by busterb** [comment]
No, it was not (was landed after we signed and released tarballs)

On Apr 17, 2017, at 4:31 AM, W. <notifications@github.com<mailto:notifications@github.com>> wrote:


Was the fix supposed to be in 2.5.3? If yes, it should be reopened since the issue still persist:

$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        libressl-2.5.3/crypto/crypto_portable.sym
