### ISSUE TITLE
Apache 2.4.26 fails to compile against LibreSSL 2.5.4

### ISSUE THREAD

**Issue by tankfeeder** [libressl-portable/portable#319]
error and patch:
https://gist.github.com/tankfeeder/6be1a7d8e5b8b107a6c94b154240d9bd
compiles now.

**Comment by 4a6f656c** [comment]
It seems that Apache 2.4.26 is requiring SSL_CTX_set_{min,max}_proto_version() - I'm not sure why you would want to "fix" it the way that you have, since this will make it compile, however the function calls (to SSL_CTX_ctrl()) will fail since those controls are unsupported.

A more appropriate workaround is to either define SSL_CTX_set_{min,max}_proto_version as unimplemented, or change the #if in ab.c to handle the LIBRESSL_VERSION case correctly - it may be possible to even get this upstreamed.

As an aside, the next release of LibreSSL (2.6.x) will contain SSL_CTX_set_{min,max}_proto_version() and it is already available in -current.

**Comment by Sp1l** [comment]
Patches upstreamed, these should appear in the next release of Apache 2.4.
https://bz.apache.org/bugzilla/show_bug.cgi?id=61184
Can find them here as well https://github.com/Sp1l/ports/tree/master/www/apache24/files
Sp1l/ports@5225544fd0db007083be7a33ea0bf1e8ee56b7eb

**Comment by tankfeeder** [comment]
i see.
