### ISSUE TITLE
Bug in RSA_padding_check_SSLv23

### ISSUE THREAD

**Issue by remyknight1119** [libressl-portable/portable#333]
I think I found a bug in libressl-2.6.0:
In RSA_padding_add_SSLv23, 8 bytes before '0' is set to 3:
```
 67 int
 68 RSA_padding_add_SSLv23(unsigned char *to, int tlen, const unsigned char *from,                                                                                                                          
 69     int flen)
 70 {
 71     int i, j;
...
 94     memset(p, 3, 8);
 95     p += 8;
 96     *(p++) = '\0';
 97 
 98     memcpy(p, from, flen);
 99     return 1;
100 }
```

But in RSA_padding_check_SSLv23, the logic of check those 8 bytes seems wrong:

```
102 int
103 RSA_padding_check_SSLv23(unsigned char *to, int tlen, const unsigned char *from,                                                                                                                        
104     int flen, int num)
105 {
106     int i, j, k;
...
121     for (i = 0; i < j; i++)
122         if (*(p++) == 0)
123             break;
124 
125     if (i == j || i < 8) {
126         RSAerror(RSA_R_NULL_BEFORE_BLOCK_MISSING);                                                                                                                                                      
127         return -1;
128     }
129     for (k = -9; k < -1; k++) {        
130         if (p[k] !=  0x03)
131             break;
132     }
133     if (k == -1) {  //when every byte of the 8 bytes == 0x03, then k == -1, but that's right, not wrong!
134         RSAerror(RSA_R_SSLV3_ROLLBACK_ATTACK);
135         return -1;
136     }
```

Please check it. Thanks!

The patch of this bug is as follows:

```
diff --git a/crypto/rsa/rsa_ssl.c b/crypto/rsa/rsa_ssl.c
index 60fc8ec..7d59c03 100644
--- a/crypto/rsa/rsa_ssl.c
+++ b/crypto/rsa/rsa_ssl.c
@@ -130,7 +130,7 @@ RSA_padding_check_SSLv23(unsigned char *to, int tlen, const unsigned char *from,
                if (p[k] !=  0x03)
                        break;
        }
-       if (k == -1) {
+       if (k != -1) {
                RSAerror(RSA_R_SSLV3_ROLLBACK_ATTACK);
                return -1;
        }
```

**Comment by 4a6f656c** [comment]
I believe the original code is correct - this implements the SSLv2/SSLv3 rollback check that TLS 1.0+ clients should support, as documented in RFC 2246 appendix E.2. A TLS capable client that is rolling back to SSL should set the last eight bytes of the RSA padding to 0x03 - if the server detects that this has been done then it knows the client supports TLS and returns a rollback attack error since it should not be connecting with SSLv2/SSLv3. The proposed change would result in a rollback attack error being returned if any of the last eight padding bytes are non-0x03.

**Comment by remyknight1119** [comment]
Thank you for your reply! 
But I think maybe you didn't understand what I want to say. Let me explain it again: if the last eight bytes of the RSA padding are all equal to 0x03, that's right, and k should be equal to -1. But in the line 133, RSA_padding_check_SSLv23 will return -1 for this case, I think that's not right.
Another evidence is, in tests/rsa_test.c, if I replace RSA_PKCS1_PADDING with RSA_SSLV23_PADDING for RSA_public_encrypt and RSA_private_decrypt, test will fail; but if I change the "if (k == -1) " to "if (k != -1) " in the 133 line of RSA_padding_check_SSLv23, test will success.

**Comment by 4a6f656c** [comment]
The k == -1 case is the case that it needs to fail on, which is what the original code does.

The purpose of this code is to detect a rollback attack - for example, an SSLv2/SSLv3 capable client attempts a connection with an SSLv2/SSLv3 capable server, however a MiTM attacker causes the SSLv3 handshake to fail. If the client supports downgrading (which is generally dangerous, but often done in order to increase interoperability), then it will try to establish a session again, but this time only advertising support for SSLv2 (since it suspects that the server may only support SSLv2 and is being buggy with SSLv3).

In order to avoid a rollback attack, the end of the RSA padding is marked with 0x3 - effectively advertising that the client is capable of SSLv3, even though it has downgraded to SSLv2. One of two things will now happen - either the server is only SSLv2 capable, at which point it will not even notice the markers at the end of the padding and continue to negotiate SSLv2... or the server supports SSLv3, in which case it should notice the markers at the end of the padding (i.e. k == -1) and as a result of the client being subject to a rollback attack, terminate the connection.

Regardless of this, these functions are no longer required by LibreSSL since we do not support either SSLv2 or SSLv3 - both `RSA_padding_{add,check}_SSLv23()` were removed prior to the last release.
