### ISSUE TITLE
possible usage of Rust language

### ISSUE THREAD

**Issue by okias** [libressl-portable/portable#340]
Hey guys,
I have very simple question: since I noticed that LibreSSL performance is very poor comparing to OpenSSL, I noticed comment that LibreSSL uses only one thread (which I guess make sense, since simpler code implementation, which can probably prevent lot of possible bugs in C code).

I wonder, if you could for critical performance parts of code use Rust language [1], which is low-level as C, but allows to use _safe_ multithreading [2] and prevents most of usual C issues.

In case of LibreSSL, I think it could be eventually possible to reach performance of OpenSSL again with very safe code.

What do you think? Are there any obstacles to make it real for LibreSSL?

[1] https://www.rust-lang.org/en-US/
[2] https://blog.rust-lang.org/2015/04/10/Fearless-Concurrency.html

**Comment by okias** [comment]
@bob-beck would you be more verbose about your decision closing bug, without any clarification why Rust doesn't make sense for LibreSSL?

**Comment by yupi2** [comment]
It would be a lot of work to port and would introduce a dependency on Rust when everything else still uses C\C++. The performance can also be improved without switching to anoter language. And learning a new language takes time. [Here](https://github.com/ctz/rustls) and [here](https://github.com/briansmith/ring) are two projects you can check out.

**Comment by 4a6f656c** [comment]
@okias - it is not a very simple question and the biggest challenge here is working out how to appropriately respond; so let me turn it around and ask you:

- You assert that "LibreSSL performance is very poor comparing to OpenSSL", but provide no further details - why are you asserting this, what tests have you done and what measurements can you provide?

- You assert that "LibreSSL uses only one thread" - why are you asserting this and why do you believe this the cause of the above mentioned performance issues? What use cases are you actually wanting to optimise for?

- You conclude that Rust is a solution to a performance "problem" that is caused by using "only one thread" - why do you believe Rust will address these issues and why would additional threads be beneficial?

- Do you have a working proof of concept that shows that Rust addresses the performance issues that you mentioned?

Aside from all of that, making Rust a dependency for LibreSSL means that LibreSSL could not be built/used on platforms where Rust is not available, including on OpenBSD systems (where LibreSSL is primarily developed) since it is not part of the base distribution.

**Comment by 4a6f656c** [comment]
@okias - closing again due to lack of response/follow up.
