### ISSUE TITLE
Android build failure

### ISSUE THREAD

**Issue by glebpom** [libressl-portable/portable#354]
Hello,

I'm getting this error when I'm trying to compile libressl v2.5.5 for android targets (specifically `i686-linux-android` and `armv7-linux-androideabi`):
```compat/getpagesize.c:10:1: error: redefinition of 'getpagesize'
getpagesize(void) {
^
/android-cross/NDK/x86/bin/../sysroot/usr/include/unistd.h:267:23: note: previous definition is here
static __inline__ int getpagesize(void) {
                      ^
1 error generated.
```

It seems like it was added in commit [8b80bcdad82a57d195381a150aa2690f188b127e](https://github.com/libressl-portable/portable/commit/8b80bcdad82a57d195381a150aa2690f188b127e). 
There is a similar issue discussed [here](https://gcc.gnu.org/ml/gcc-patches/2015-11/msg00675.html), which explains why configuration system fails to detect `getpagesize` function with AC_CHECK_FUNCS test. 

Versions <2.5.5 fails with another error:

```
compat/getpagesize.c:4:10: fatal error: 'windows.h' file not found
#include <windows.h>
         ^~~~~~~~~~~
1 error generated.
make[1]: *** [compat/getpagesize.lo] Error 1
```
The lates working version is 2.5.1

**Comment by yan12125** [comment]
LibreSSL 2.6.3 + NDK r16 beta 2 builds fine for me. Just that I can't specify root CA path with ```$SSL_CERT_DIR``` [1] so using it is a little bit tricky :)

[1] https://marc.info/?l=openbsd-ports&m=144578740817527&w=2

**Comment by kinichiro** [comment]
@glebpom Does this issue still remain ?

**Comment by molind** [comment]
Checked libressl 2.6.3 on NDK r16. Still fails to build:

```
compat/getpagesize.c:10:1: error: redefinition of 'getpagesize'
getpagesize(void) {
^
/Volumes/raid/git/libs/toolchain/arm/bin/../sysroot/usr/include/unistd.h:282:23: note: previous definition is here
static __inline__ int getpagesize(void) {
                      ^
1 error generated.
```

**Comment by molind** [comment]
Have to patch check-libc.m4 to build it for Android. Configure fails to find getpagesize because it's defined as inline function inside unistd.h. And we needed to include unistd.h on android to check if it works correctly.

diff -rupN libressl-2.6.3/m4/check-libc.m4 libressl-patched/m4/check-libc.m4 
--- libressl-2.6.3/m4/check-libc.m4	2017-11-04 23:04:56.000000000 +0300
+++ libressl-patched/m4/check-libc.m4	2017-11-23 13:48:59.000000000 +0300
@@ -2,10 +2,23 @@ AC_DEFUN([CHECK_LIBC_COMPAT], [
 # Check for libc headers
 AC_CHECK_HEADERS([err.h readpassphrase.h])
 # Check for general libc functions
-AC_CHECK_FUNCS([asprintf freezero getpagesize inet_ntop inet_pton memmem])
+AC_CHECK_FUNCS([asprintf freezero inet_ntop inet_pton memmem])
 AC_CHECK_FUNCS([readpassphrase reallocarray recallocarray])
 AC_CHECK_FUNCS([strlcat strlcpy strndup strnlen strsep strtonum])
 AC_CHECK_FUNCS([timegm _mkgmtime])
+AC_CACHE_CHECK([for getpagesize], ac_cv_func_getpagesize, [
+	AC_LINK_IFELSE([AC_LANG_PROGRAM([[
+// Since Android NDK v16 getpagesize is defined as inline inside unistd.h
+#ifdef __ANDROID__
+#	include <unistd.h>
+#endif
+		]], [[
+	getpagesize();
+]])],
+	[ ac_cv_func_getpagesize="yes" ],
+	[ ac_cv_func_getpagesize="no"
+	])
+])
 AM_CONDITIONAL([HAVE_ASPRINTF], [test "x$ac_cv_func_asprintf" = xyes])
 AM_CONDITIONAL([HAVE_FREEZERO], [test "x$ac_cv_func_freezero" = xyes])
 AM_CONDITIONAL([HAVE_GETPAGESIZE], [test "x$ac_cv_func_getpagesize" = xyes])

**Comment by kinichiro** [comment]
Could you post it as pull request, please ?

**Comment by molind** [comment]
Sure.

**Comment by yan12125** [comment]
I think I know why I didn't get this error - I built LibreSSL against Android L (Lollipop, API 21), and getpagesize is a normal (non-inline) function in this Android version.
```C
#if __ANDROID_API__ >= __ANDROID_API_L__
int getpagesize(void) __INTRODUCED_IN(21);
#else
static __inline__ int getpagesize(void) {
  return sysconf(_SC_PAGESIZE);
}
#endif
```

**Comment by kinichiro** [comment]
@molind Thanks. #363 had solved this issue.

**Comment by AmarOk1412** [comment]
Hei! I just compiled libressl for Android and I get this issue due to crypto/compat/getpagesize.c

**Comment by Depau** [comment]
Does this patch work when I'm building it using CMake or am I doing something wrong?

I'm including it into my app like this:

`app/CMakeLists.txt`
```
cmake_minimum_required(VERSION 3.4)
execute_process(COMMAND ./autogen.sh
    WORKING_DIRECTORY src/c/libressl)
add_subdirectory(src/c/libressl)
```

`src/c/libressl` is this repo.

It seems to build fine until it stops with the same error as above.

**Comment by Depau** [comment]
Does this patch work when I'm building it using CMake or am I doing something wrong?

I'm including it into my app like this:

`app/CMakeLists.txt`
```
cmake_minimum_required(VERSION 3.4)
execute_process(COMMAND ./autogen.sh
    WORKING_DIRECTORY src/c/libressl)
add_subdirectory(src/c/libressl)
```

`src/c/libressl` is this repo.

It seems to build fine until it stops with the same error as above.
