### ISSUE TITLE
LibreSSL 2.6 broke CPython's test_npn_protocols

### ISSUE THREAD

**Issue by tiran** [libressl-portable/portable#368]
CPython's ``test_npn_protocols`` is broken since LibreSSL 2.6.1. The same test passes with previous versions of LibreSSL (2.6.0, 2.5.5, and earlier).

```
======================================================================
FAIL: test_npn_protocols (test.test_ssl.ThreadedTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/heimes/dev/python/cpython/Lib/test/test_ssl.py", line 3424, in test_npn_protocols
    self.assertEqual(client_result, expected, msg % (client_result, "client"))
AssertionError: None != 'http/1.1' : failed trying ['http/1.1', 'spdy/2'] (s) and ['http/1.1', 'spdy/2'] (c).
was expecting http/1.1, but got None from the client
```

## reproducer

```
git clone https://github.com/python/cpython.git``
cd cpython
./configure -C
make
./python Tools/ssl/multissltests.py --libressl 2.5.5 2.6.0 2.6.1
```

**Comment by kinichiro** [comment]
NPN was removed since 2.6.1
https://raw.githubusercontent.com/libressl-portable/portable/master/ChangeLog.
https://github.com/libressl-portable/openbsd/commit/23c27360840a38f46be57df99b8664695281d39b

But it could not define OPENSSL_NO_NEXTPROTONEG at this time to avoid other projects build break.
https://github.com/libressl-portable/openbsd/commit/e397911508fafbd43be04cf88d845df332969ec9

**Comment by 4a6f656c** [comment]
As already noted, NPN has been removed - unfortunately we could not fully remove the interfaces and define OPENSSL_NO_NEXTPROTONEG, since it breaks multiple projects (all in different ways). In the case of cPython it will be failing since it is negotiating with itself and expecting a particular outcome - the best option is to condition on the availability of `TLSEXT_TYPE_next_proto_neg` since we were able to remove this and it will be present in LibreSSL/OpenSSL when NPN is available/functional.

**Comment by 4a6f656c** [comment]
@tiran is it possible to condition these tests on the availability of `TLSEXT_TYPE_next_proto_neg`? There is not much that LibreSSL can do here for the reasons previously mentioned.

**Comment by 4a6f656c** [comment]
Closing this since there is nothing that LibreSSL can really do, short of actually re-adding support for NPN.

**Comment by Sp1l** [comment]
Meanwhile, Python properly supports building without NPN support. This is also necessary for OpenSSL 1.1.x configured no-nextprotoneg.
NPN is deprecated and has since been replaced with ALPN...
