### ISSUE TITLE
Q: Add DTLS 1.2 support in LibreSSL

### ISSUE THREAD

**Issue by signmgr** [libressl-portable/portable#380]
Hi,

Are there any plans to add the support for DTLS 1.2?
If yes, what is the road map for that?

Thanks in advance!

/Misha

**Comment by signmgr** [comment]
Hi,

Can anyone answer about the plans to include DTLS 1.2 support in LibreSSL?

Thanks a lot in advance!

/Misha

**Comment by 4a6f656c** [comment]
It will happen, but at this stage it is not a super high priority. There has been a lot of work done to deduplicate the DTLS/TLS code (the original DTLS code was effectively a copy and paste of the SSLv3/TLS code, with minor changes) - this makes it relatively easy to now enable DTLSv1.2 and I have a tree that does most of this, but it needs some more time and effort from someone, in order to finish the job.

**Comment by signmgr** [comment]
Hi Joel,

Thanks a lot for your response!

May I also wonder about the future of DTLS/SCTP support?
As I know DTLS/SCTP support was removed since LibreSSL v2.1.4.
Are there any plans to return the functionality back after you have finished with DTLS/TLS decoupling?

Thanks a lot in advance!

/Misha

**Comment by tuxillo** [comment]
Still not supported?

**Comment by kinichiro** [comment]
Expose various DTLSv1.2 specific functions and defines
https://github.com/openbsd/src/commit/e6d88397616a72165a937474dab56c25efd3d032

**Comment by 4a6f656c** [comment]
Support for DTLSv1.2 is available in the current development release (3.3.2) and will be available in the next stable release.
