### ISSUE TITLE
What is the correct Libressl source code location?

### ISSUE THREAD

**Issue by bagajjal** [libressl-portable/portable#385]
Hi,

We are shipping LibreSSL into windows.

We plan to create our own GitHub repo for the shipped LibreSSL version.
This is required to backport security fixes (if any) to our shipped LibreSSL version.

I came across two different LibreSSL source code locations,
1) GitHub LibreSSL portable (this GitHub repo).
2) Official release distribution from https://ftp.openbsd.org/pub/OpenBSD/LibreSSL

I see a lot of files that exist in one repo but not in another repo.

For example,
1)	GitHub repo contains "patches" (directory), "libtls-standalone" (directory), update.sh, OPENBSD_BRANCH, dist.sh, etc. that doesn't exist in official release distribution source code.
2)	Official release distribution source code contains source files (*.c, *.h files) in "tls" (directory), "tests" (directory), etc. that doesn’t exist in the GitHub repo.

We built our binaries using official release distribution source code.
If we go with this approach, then it’s not possible to cherry pick the desired security fixes.
We must manually do the code changes.

What is the best way to avoid manual code changes?

Thanks,
Balu

**Comment by Johnex** [comment]
Well thats the thing. This repo is only for the portable aspect of LibreSSL, making it work on windows for example. The source code here is made into patches that are patched onto the official one on each release (from what i understand).

I guess what you could do is to make your own repo somewhere, where you can download and apply patches to the official code when needed, and you can then cherry pick from that repo you made.

I think its made like that because the official repo guys didn't want windows patches and so on to exist in the linux code tree.

**Comment by busterb** [comment]
If you wanted to cherry-pick changes, you'd need to fork this repo and the libressl-portable/portable repo. Put your patches in a branch, update OPENBSD_BRANCH or update.sh to pull from the right place, then run autogen.sh to merge the code. Look at how all of the other stable release branches in this repo do it.

Or just use the official releases.
