### ISSUE TITLE
Adding support for SSL_add1_chain_cert and SSL_add0_chain_cert ?

### ISSUE THREAD

**Issue by normanmaurer** [libressl-portable/portable#430]
Are there any plans to add the following API:

SSL_add1_chain_cert(...)
SSL_add0_chain_cert(...)

Both are documented here:

https://www.openssl.org/docs/man1.1.1/man3/SSL_add1_chain_cert.html

We depend on these in https://github.com/netty/netty-tcnative for some features which we currently can not support when LibreSSL is used.

**Comment by botovq** [comment]
On Thu, Jun 28, 2018 at 07:36:42PM +0000, Norman Maurer wrote:
> Are there any plans to add the following API:
> 
> SSL_add1_chain_cert(...)
> SSL_add0_chain_cert(...)

Yes, we definitely want to add these and related functions and would
love to have these done sooner rather than later. Unfortunately, this
needs a non-trivial amount of rather involved work that still has to be
done. Ideally, this would make the next major release this fall.

**Comment by sephiroth-j** [comment]
Seems to be part of v2.9.2 (https://github.com/libressl-portable/openbsd/commit/0db809ee178457c8170abfae3931d7bd13abf3ef)

**Comment by normanmaurer** [comment]
@sephiroth-j yes ... thanks a lot!
