### ISSUE TITLE
Support of Cryptographic Message Syntax

### ISSUE THREAD

**Issue by misery** [libressl-portable/portable#448]
I like to request support of Cryptographic Message Syntax.
https://tools.ietf.org/html/rfc5652

It is meaningful in some applications which uses it so parse ASN.1 stuff. OpenSSL supports it. Maybe this could be introduced to switch from openssl to libressl.

Support of S/MIME is not necessary!

**Comment by 4a6f656c** [comment]
Could you elaborate on your use case and how much of the CMS functionality you require?

The CMS code was removed from libcrypto, since it added around 7,000 lines of code that needed significant clean up/maintenance and had potential security issues - very few things actually used it then. We wouldn't be completely opposed to supporting it, however it would either need to be a clean implementation or have someone who is prepared to clean it up and maintain it.

**Comment by misery** [comment]
By the way... you can try AusweisApp2 with libressl and it will show you the missing CMS support and required API.

https://github.com/Governikus/AusweisApp2

**Comment by misery** [comment]
Maybe this (https://github.com/libressl-portable/portable/commit/dd210a6fc3e621feadfb212031e596eb18c252e5) is a partial fix?

**Comment by busterb** [comment]
Good eye! That'll be done when CMS support is fully enabled upstream. I added that in the short term to facilitate compiling the latest, which has some header dependencies.

**Comment by skeyby** [comment]
Hello, I'd like to ask for CMS clarification as well, as CMS is a obligatory tool to check for Digital Signature according to eIdas regulation...

**Comment by kinichiro** [comment]
OPENSSL_NO_CMS was removed and CMS was enabled in LibreSSL https://github.com/libressl-portable/openbsd/commit/0684ef30f589bb4c99f55a689dc35a596374d60f .

**Comment by 4a6f656c** [comment]
CMS support is available in LibreSSL 3.1.0 and will be in the next stable release.
