### ISSUE TITLE
Support `$ENV::FOO` interpolations

### ISSUE THREAD

**Issue by wiml** [libressl-portable/portable#463]
A problem that people run into when using the libressl command line tools is that they don't support interpolating strings from the environment the way openssl does.

**Comment by busterb** [comment]
Can you give an example?

**Comment by busterb** [comment]
A specific example of what you're trying to do.

**Comment by busterb** [comment]
http://openbsd-archive.7691.n7.nabble.com/LibreSSL-openssl-cnf-and-using-ENV-to-pass-values-td300942.html explains the current state of ENV interpolations and some hints on why they were removed from the core library.

This github project is really just for the portable bits. I think if you wanted to raise the case for this feature generally (since the code that was removed is in the upstream OpenBSD project), you'll probably get a better response on the @openbsd mailing lists than here.
