### ISSUE TITLE
About disabling Compiler Warnings in CMake

### ISSUE THREAD

**Issue by Dravion** [libressl-portable/portable#504]
Hi,
In the Project CMakeLists.txt, there are some switches iam a bit confused about.
Can you explain, why you disable this list of warnings instead of solving the circumstances
which causes the warnings in the first place?

 if(CMAKE_C_COMPILER_ID

 MATCHES "MSVC")
		set(MSVC_DISABLED_WARNINGS_LIST
			"C4018" # 'expression' : signed/unsigned mismatch
			"C4057" # 'operator' : 'identifier1' indirection to
		        	# slightly different base types from 'identifier2'
			"C4100" # 'identifier' : unreferenced formal parameter
			"C4127" # conditional expression is constant
			"C4146" # unary minus operator applied to unsigned type,
				# result still unsigned
			"C4244" # 'argument' : conversion from 'type1' to 'type2',
				# possible loss of data
			"C4245" # 'conversion' : conversion from 'type1' to 'type2',
				# signed/unsigned mismatch
			"C4267" # 'var' : conversion from 'size_t' to 'type',
				# possible loss of data
			"C4389" # 'operator' : signed/unsigned mismatch
			"C4706" # assignment within conditional expression
			"C4996" # The POSIX name for this item is deprecated.
				# Instead, use the ISO C and C++ conformant name
		)

I can understand why you disabling something like this:
"C4996" # The POSIX name for this item is deprecated.
		# Instead, use the ISO C and C++ conformant name

This make total sense to me, but what about this?

"C4018" # 'expression' : signed/unsigned mismatch
"C4267" # 'var' : conversion from 'size_t' to 'type',	# possible loss of data
"C4389" # 'operator' : signed/unsigned mismatch

?

**Comment by Johnex** [comment]
Well a lot of the signed/unsigned happens with things that don't really matter, like SOCKET being an unsigned value, but all return types in posix functions being signed values. Microsoft decided not to follow the Berkley sockets standard completely, and that causes a lot of warnings. Since LibreSSL works on many platforms, having some casts just for windows would be pointless, and since they don't really cause any issues, better just hide the warnings.

**Comment by busterb** [comment]
That is correct, thanks for the explanation @Johnex.
