### ISSUE TITLE
Replace WinCrypt with Cryptography API: Next Generation

### ISSUE THREAD

**Issue by feliwir** [libressl-portable/portable#545]
As i was using LibreSSL for a WindowsStore project i noticed that the old Wincrypt API is not accesible anymore (it's also marked as deprecated on MSDN). The correct behaviour now is to use the new Cryptography API: Next Generation:
https://docs.microsoft.com/en-us/windows/win32/seccng/cng-portal

It is available from Windows Vista and onwards and should be fine for us to use.
@kinichiro

**Comment by feliwir** [comment]
Can i get any feedback on this issue please? More than one year has passed

**Comment by busterb** [comment]
Hi @feliwir did you send a patch or pull request? I might have missed it, though I'm guessing you've tried something in the mean time. Were you thinking of this as a replacement for CryptAcquireContext / CryptGenRandom / CryptReleaseContext?
https://docs.microsoft.com/en-us/windows/win32/api/bcrypt/nf-bcrypt-bcryptgenrandom

We might have originally avoided it due to mingw-w64 not exporting it earlier, but will double-check.

**Comment by feliwir** [comment]
@busterb 

Hey, i had this already implemented but filled no PR, since i was not sure if this is viable for you, since i think the legacy crypt functions are used in other places aswell. However the getentropy function was the only conflict i got for windows store. See my implementation below:
```c
int
getentropy(void *buf, size_t len)
{
	if (len > 256) {
		errno = EIO;
		return (-1);
	}

	if (FAILED(BCryptGenRandom(NULL, (BYTE*)buf, len, BCRYPT_USE_SYSTEM_PREFERRED_RNG)))
	{
		errno = EIO;
		return (-1);
	}

	return (0);
}
```

**Comment by busterb** [comment]
Cool, thanks. I'll can put up a PR for review and we can see how it fares on the regression tests. Since this code is used by other portable projects outside of LibreSSL (the source is upstream in the OpenBSD tree), will need to make sure that it works fine for them. I imagine it'll be OK, since these new functions have been around since Vista/2008.

**Comment by busterb** [comment]
Hmm, looks like we'll need to tweak mingw to link -lbcrypt and probably the VS targets too. Also found a fun bug in the mingw-w64 headers where FORTIFY_SOURCE=2 doesn't link anymore, at least in the latest Debian packages included, so will also need to merge something like this fix https://github.com/LibreDWG/libredwg/commit/e81649ce78fb346b2a7fda4b4ecb5bfa3caec3e8

**Comment by feliwir** [comment]
Can this please get merged into upstream anytime soon? We need to manually patch each LibreSSL version to compile for Windows Store
