### ISSUE TITLE
Please, could you tag releases?

### ISSUE THREAD

**Issue by AsavarTzeth** [libressl-portable/portable#56]
If you could tag the releases that go into your tar balls I would very much appreciate it.

Fetching & building directly from your repository, using git sub-modules, would greatly simplify work in my project.

**Comment by busterb** [comment]
I haven't done this yet because in the CVS->Git conversion for the OpenBSD tree, if I find we need to add a new CVS directory, it rewrites all of the history to that point the new directory was added, breaking the hashes for the submodule references.

Case in point, I'm looking at adding the regress/usr.sbin/openssl path to the CVS import, but have been avoiding it for a little while to avoid any disruption with forks. Same thing for when the 'libressl' library was added, and later the move to 'libtls'. Maybe once directory motion settles down, we can consider tagging.

**Comment by AsavarTzeth** [comment]
Okay, it is not a critical issue to me. Thank you for your detailed explanation of the issue.

Since you have a good reason for things being the way they are and this is just a minor workflow issue to me, I will close this issue. At least I have made my voice heard on the topic and that is enough for me.
