### ISSUE TITLE
Add mingw64 build to Travis CI

### ISSUE THREAD

**Issue by jbarlow83** [libressl-portable/portable#57]
Since mingw/mingw64 is a supported platform, it would be ideal to set it up for continuous integration - preferably a true Windows build or a Ubuntu to Windows cross compile.

**Comment by busterb** [comment]
Do you know how to do it nicely? I've seen folks suggesting installing the cross-compiler on the Linux builders as part of the build process, but the Travis VMs run Ubuntu 12.04 which has old compilers.

I can probably setup something on my jenkins server.

**Comment by jbarlow83** [comment]
I know almost nothing about Travis. What's the problem with the old Travis
compilers? Do they not support hardening, or do they choke on other things?

I think having simple automatic build checks on every platform anyone cares
about is more important than getting ideal builds for all platforms. My
thought is work around Travis - give it what flags it needs to build with
its old compilers (if it can work at all) and bug them to upgrade their VMs
some time. Keep it simple.

**Comment by busterb** [comment]
More specifically, I have had issues with the mingw compilers from Ubuntu 12.04 because the headers and runtime it packaged were not as complete, so you couldn't call all of the Windows APIs. Not because of the gcc version specifically. I'll give it a try - it may be possible to just point it to the mingw PPA for a backport if needed.

**Comment by busterb** [comment]
Got it working - what a pain though!

https://travis-ci.org/libressl-portable/portable
