### ISSUE TITLE
mipsisa32: arc4random.c:90: undefined reference to `getentropy'

### ISSUE THREAD

**Issue by jensolsson** [libressl-portable/portable#580]
Hi

I am trying to cross compile libressl to a mips environment.

For configuring I run the following commands and it seem to work well:
export PREFIX=/usr/local/mipsisa32r2el/r23/bin
export TARGET=mipsisa32r2el-axis-linux-gnu
export CC=/usr/local/mipsisa32r2el/r23/bin/mipsisa32r2el-axis-linux-gnu-gcc
export CXX=/usr/local/mipsisa32r2el/r23/bin/mipsisa32r2el-axis-linux-gnu-g++
export LD=/usr/local/mipsisa32r2el/r23/bin/mipsisa32r2el-axis-linux-gnu-ld
./configure --disable-shared --without-pic --host=x86-32

However then I execute "make" and it also seem to work well until it stops looking for a getentropy function that seem to be missing.

If anyone have a clue on how to patch the code so I can continue, or maybe I made a mistake and some lib is missing etc? Any help would be greatly appreciated

Making all in apps
make[1]: Entering directory `/home/libressl-portable/apps'
Making all in ocspcheck
make[2]: Entering directory `/home/libressl-portable/apps/ocspcheck'
  CCLD     ocspcheck
/home/libressl-portable/crypto/.libs/libcrypto.a(arc4random.o): In function `_rs_stir':
/home/libressl-portable/crypto/compat/arc4random.c:90: undefined reference to `getentropy'
collect2: error: ld returned 1 exit status

**Comment by kinichiro** [comment]
Hi,

I do not have that cross compiler environment, and I can not try it, though,
does specifying `--host=mipsisa32r2el-axis-linux-gnu` for `configure` script
instead of `x86-32` solve your issue ?

I guess your cross compile target does not have getentropy,
so I think you need to tell `configure` to inlude getentropy support.

LibreSSL provides getentropy support for several platforms that doesn't have it.
You can see them as `crypto/compat/getentropy_*.c`.
if `HAVE_GETENTROPY` is set to false in `crypto/Makefile.am.arc4random` 
these getentropy support is included, according to host type (ex. `HOST_LINUX`).
`HAVE_GETENTROPY` and host type are checked by `configure` script.
If the host type does not match the platform that LibreSSL prepare the getentropy,
`configure` can not include getentropy. 

`--host=mipsisa32r2el-axis-linux-gnu` will tell `configure` that the host type is HOST_LINUX
and will indicate to include crypto/compat/getentropy_linux.c for your build.

I hope this help you.

**Comment by kinichiro** [comment]
@jensolsson do you still have this issue ? Are there any updates for this ?

**Comment by 4a6f656c** [comment]
Closing due to lack of response.
