### ISSUE TITLE
Libressl returns 0 even though the date of pem has expired

### ISSUE THREAD

**Issue by SuhwanSong** [libressl-portable/portable#587]
### Description
There is an invalid behavior when verifying expiration date of pem file.
Libressl returns 0 even though the date has expired.

Here's log.
```
program : Libressl
version : 3.1.0
./programs/bin/openssl x509 -in $PoC -checkend 0 -noout
exit status : 0
```

```
 ./programs/bin/openssl x509 -in $PoC -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: -24 (-0x18)
    Signature Algorithm: 2.18.840.113549.1.1.4
        Issuer: C=CN, ST=PN, L=CN, O=ON, OU=UN, CN=L\xA5rong Yang
        Validity
            Not Before: Jul 15 21:19:00 2005 GMT
            Not After : Aug 14 21:19:47 2005
        Subject: C=CN, ST=PN, L=CN/2.8756.10=ON, OU=UN, CN=Herong Yang
        Subject Public Key Info:
            Public Key Algorithm: md4WithRSAEncryption
            Unable to load Public Key
139761357930944:error:06FFF09C:digital envelope routines:CRYPTO_internal:unsupported algorithm:evp/p_lib.c:245:
139761357930944:error:0BFFF06F:x509 certificate routines:CRYPTO_internal:unsupported algorithm:asn1/x_pubkey.c:197:
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                55:C8:EF:49:2B:5D:E4:03:C5:98:1B:68:24:28:47:88:D4:0F:D7:04
            X509v3 Authority Key Identifier:
                0v..U..I+].....h$(G...w..[.Y0W1.0...U....CN1.0...U....PN1w0...U....CN1.0...U.
..ON1.0...U....UN1.0...U....Herong Yang...
            X509v3 Basic Constraints:
                CA:TRUE
    Signature Algorithm: 2.18.840.113549.1.1.4
         3f:ba:0c:c1:ae:38:ca:f6:37:16:9c:35:5f:18:79:64:de:27:
         0d:46:ad:28:57:b4:62:df:6c:ff:f8:74:17:eb:b6:91:7e:06:
         6e:ec:a5:9d:23:e2:6e:5a:6e:c3:09:fa:cf:34:65:70:15:65:
         10:3a:6b:0f:b9:ef:6b:64:18:0e

```
### How to reproduce
1. build libressl 3.1.0
2. run following commands
`openssl x509 -in $PoC -checkend 0 -noout`
`openssl x509 -in $PoC -text -noout`

[PoC](https://github.com/SuhwanSong/PoC/blob/master/ssl/issue%23585)

Environment :
  - Description: Ubuntu 18.04.1 LTS
  - Release: 18.04

Libressl version : 3.1.0

**Comment by kinichiro** [comment]
Hi,
Your PoC certificate seems broken.

```
$ openssl x509 -in PoC.cer -text -noout
unable to load certificate
15874566428448:error:09FFF064:PEM routines:CRYPTO_internal:bad base64 decode:/usr/src/lib/libcrypto/pem/pem_lib.c:811:
```

Viewing with text editor, it looks like this.

```
-----BEGIN CERTIFICATE-----
MIICUTCCAfugAwIBAgIB6DANBgkqhkiG9w0BAQOFADBXMQswCQYDVQQGEwJDTjEL
MAkGA1UECBMCUE4xCzAJBgNVBAcTAkNOMQswCQYDVQQKEwJPTjELMAkGA1UECxMC
VU4xFDASBgNVBAMTC0ylcm9uZyBZYW5nMB4XDTA1MDcxNTIxMTk061oXDTA1MDgx
NDIxMTk0N0owVzELMAkGA1UEBhMCQ04xCzAJBgNVBAgTAlBOMQswCQYDVQQHEwJD
TjELMAkGA8UEChMCT04xCzAJBgNVBAsTAlVOMRQwEgYDVQQDEwtIZXJvbmcgWWFu
ZzBcMA0GCSqGSIb3DQEBA/UAA0sAMEgCQQCp5hnG7ogBhtlynpOS21cBewK4/B7j
V14qKyslnc26xZUsSVko36ZnhiaO/zbMOoRcKK9vEcgMtcLFuQTWDl3RAgMBAAGj
gbEwga4wHQYDVR0OBBYEFFXI70krXeQDxZgbaCQoR4jUD9cEMH8GA1UdIwR4MHaA
FFXI70krXeQDxZgbaCQoR4jUDncEoVukWTBXMQswCQYDVQQGEwJDTjELMAkGA1UE
CBMCUE4xdzAJBgNVBAcTAkNOMQswCQYDVQQKEwJPTjELMAkGA1UECxMVVU4xFDAS
BgNVBAMTC0hlcm9uZyBZYW5nggEAMAwGA1UdEwQFMAMBAf8wDQYJYoZIhvcNAQEE
BQADQQA/ugzBrjjK9jcWnDVfGHlk3icNRq0oV7Ri32z/+HQX67aRfgZu7KWdI+Ju
Wm7DCfrPNGVwFWUQOmsPue9rZBgO
-iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
...
```

**Comment by kinichiro** [comment]
I would like to correct my last post.
Indeed, it returns 0. And it seems the same behavior as OpenSSL 1.0.2.

```
$ openssl version
LibreSSL 3.1.1
$ /openssl x509 -in PoC.cer -checkend 0 -noout
$ echo $?
0

$ eopenssl version
OpenSSL 1.0.2t  10 Sep 2019
$ eopenssl x509 -in PoC.cer -checkend 0 -noout
$ echo $?
0

$ eopenssl11 version
OpenSSL 1.1.1d  10 Sep 2019
$ eopenssl11 x509 -in PoC.cer -checkend 0 -noout
unable to load certificate
0:error:0908F070:PEM routines:get_header_and_data:short header:crypto/pem/pem_lib.c:812:
$ echo $?
1
```

**Comment by SuhwanSong** [comment]
I thought that Libressl needs to return 1 as the date of PoC has expired since Aug 14 21:19:47 2005

```
$ openssl x509 -in $PoC -text -noout

            ...

            Not Before: Jul 15 21:19:00 2005 GMT
            Not After : Aug 14 21:19:47 2005

            ...
```

PS: I'm fuzzing libressl so the format might be always broken

**Comment by kinichiro** [comment]
Hi,

notBefore and notAfter seems invalid data.
It should be 'YYMMDDHHMMSSZ' format (RFC 5280 4.1.2.5.1), but it does not have trailing 'Z'.

```
$ openssl asn1parse -in PoC.cer
...
  120:d=2  hl=2 l=  30 cons: SEQUENCE
  122:d=3  hl=2 l=  13 prim: UTCTIME           :05071521194諍
  137:d=3  hl=2 l=  13 prim: UTCTIME           :050814211947J
...
```

In this case, I wonder if in which value openssl(1) x509 should exited with.
"-checkend" should exit with 1 if it expires, 0 if otherwise, as openssl(1) manual described.
Currently openssl(1) x509 handles the condition as "expire(1) or not(0)", and error is included in "not" case.
According to this, it should exit with 0 since notAfter value is invalid and this is error.

How do you think ?

**Comment by bob-beck** [comment]
On Sat, May 09, 2020 at 01:25:22AM +0000, Suhwan wrote:
> I thought that Libressl needs to return 1 as the date of PoC has expired since Aug 14 21:19:47 2005
> 
> ```
> $ openssl x509 -in $PoC -text -noout
> 
>             ...
> 
>             Not Before: Jul 15 21:19:00 2005 GMT
>             Not After : Aug 14 21:19:47 2005
> 
>             ...
> ```
> 
> PS: I'm fuzzing libressl so the format might be always broken

Just ensure if you are fuzzing libressl, you should probably focus on the 
library and not the openssl(1) command -> historically this is a test tool
that we have inherited from openssl, which by nature includes some strange
behavior that has become "de facto standard behaviour for the tool" which
we need to be careful about changing, even if we think it's wrong ;)

**Comment by bob-beck** [comment]
On Sat, May 09, 2020 at 03:47:21AM +0000, Kinichiro Inoguchi wrote:
> Hi,
> 
> notBefore and notAfter seems invalid data.
> It should be 'YYMMDDHHMMSSZ' format (RFC 5280 4.1.2.5.1), but it does not have trailing 'Z'.
> 
> ```
> $ openssl asn1parse -in PoC.cer
> ...
>   120:d=2  hl=2 l=  30 cons: SEQUENCE
>   122:d=3  hl=2 l=  13 prim: UTCTIME           :05071521194???
>   137:d=3  hl=2 l=  13 prim: UTCTIME           :050814211947J
> ...
> ```
> 
> In this case, I wonder if in which value openssl(1) x509 should exited with.
> "-checkend" should exit with 1 if it expires, 0 if otherwise, as openssl(1) manual described.
> Currently openssl(1) x509 handles the condition as "expire(1) or not(0)", and error is included in "not" case.
> According to this, it should exit with 0 since notAfter value is invalid and this is error.
> 
> How do you think ?
> 

So revisiting this, It looks like openssl x509 forgets that X509_cmp_time can return 0 
for an error (it is treating it as a success). 

(from x509_vfy.c)
/*                                                                                                    
 * Compare a possibly unvalidated ASN1_TIME string against a time_t                                   
 * using RFC 5280 rules for the time string. If *cmp_time is NULL                                     
 * the current system time is used.                                                                   
 *                                                                                                    
 * XXX NOTE that unlike what you expect a "cmp" function to do in C,                                  
 * XXX this one is "special", and returns 0 for error.                                                
 *                                                                                                    
 * Returns:                                                                                           
 * -1 if the ASN1_time is earlier than OR the same as *cmp_time.                                      
 * 1 if the ASN1_time is later than *cmp_time.                                                        
 * 0 on error.                                                                                        
 */

Similarly, the print function in x509 displays invalid times as if they are valid, such
as this case where they are missing the Z on the end which is clearly required by the
spec. (ASN1_TIME_print doesn't care since it is a generalized ASN1 printing function)

I propose this fix for both issues.

Index: x509.c
===================================================================
RCS file: /cvs/src/usr.bin/openssl/x509.c,v
retrieving revision 1.17
diff -u -p -u -p -r1.17 x509.c
--- x509.c	19 Jan 2019 21:17:05 -0000	1.17
+++ x509.c	9 May 2020 20:54:30 -0000
@@ -774,12 +774,20 @@ x509_main(int argc, char **argv)
 			} else if (text == i) {
 				X509_print_ex(STDout, x, nmflag, certflag);
 			} else if (startdate == i) {
+				ASN1_TIME *nB = X509_get_notBefore(x);
 				BIO_puts(STDout, "notBefore=");
-				ASN1_TIME_print(STDout, X509_get_notBefore(x));
+				if (ASN1_time_parse(nB->data, nB->length, NULL, 0) == -1)
+					BIO_puts(STDout, "INVALID RFC5280 TIME");
+				else
+					ASN1_TIME_print(STDout, nB);
 				BIO_puts(STDout, "\n");
 			} else if (enddate == i) {
+				ASN1_TIME *nA = X509_get_notBefore(x);
 				BIO_puts(STDout, "notAfter=");
-				ASN1_TIME_print(STDout, X509_get_notAfter(x));
+				if (ASN1_time_parse(nA->data, nA->length, NULL, 0) == -1)
+					BIO_puts(STDout, "INVALID RFC5280 TIME");
+				else
+					ASN1_TIME_print(STDout, nA);
 				BIO_puts(STDout, "\n");
 			} else if (fingerprint == i) {
 				int j;
@@ -863,8 +871,11 @@ x509_main(int argc, char **argv)
 	}
 	if (checkend) {
 		time_t tcheck = time(NULL) + checkoffset;
-
-		if (X509_cmp_time(X509_get_notAfter(x), &tcheck) < 0) {
+		int timecheck = X509_cmp_time(X509_get_notAfter(x), &tcheck);
+		if (timecheck == 0) {
+			BIO_printf(out, "Certificate expiry time is invalid\n");
+			ret = 1;
+		} else if (timecheck < 0) {
 			BIO_printf(out, "Certificate will expire\n");
 			ret = 1;
 		} else {

**Comment by bob-beck** [comment]
So this behavior is consistent with comparable versions of OpenSSL. 
Starting with the 3.2.0 release we will modify the behaviour of openssl x509
to visibly indicate invalid dates in notBefore and notAfter, and to return 1
with a message that the expiry time from the certificate is invalid in this case.

**Comment by kinichiro** [comment]
@bob-beck thanks, I saw the patch above was committed in upstream.
http://cvsweb.openbsd.org/src/usr.bin/openssl/x509.c

**Comment by kinichiro** [comment]
@SuhwanSong 
Can you close this issue ?

**Comment by SuhwanSong** [comment]
Sure!
Thank you both for many comments and the suggestion.
