### ISSUE TITLE
VirtualAlloc not supported for UWP

### ISSUE THREAD

**Issue by feliwir** [libressl-portable/portable#638]
Hello,

arc4random_win.h does not work correctly for UWP platforms. Eventhough the code does compile, the function does not allocate any memory. See the supported platforms for reference: https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualalloc

**Comment by kinichiro** [comment]
Hi,

Just replacing `VirtualAlloc` with `VirtualAllocFromApp` works for you on UWP ?
https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualallocfromapp

**Comment by feliwir** [comment]
@kinichiro my colleague tested it and says it didn't work for him. Can't test it myself, since i'm on a linux machine. We replaced it by a regular **malloc**

**Comment by kinichiro** [comment]
@feliwir  Thanks for your report.

I had tested with Visual Studio 2019 (16.9.5) on my local Windows10 PC.

I built libressl-3.3.3.tar.gz for UWP configuration with this cmake command.
```
cmake -G "Visual Studio 16 2019" -DCMAKE_SYSTEM_NAME=WindowsStore 
    -DCMAKE_SYSTEM_VERSION=10.0 -DBUILD_SHARED_LIBS=on ..
```

When I was debugging `ecdsatest`, I saw `VirtualAlloc` in `_rs_allocate` (arc4random_win.h) succeeded and returned non-null address, but allocated memory was "Unable to read memory".
![uwp-1](https://user-images.githubusercontent.com/4927823/118372325-0d00d600-b5ec-11eb-81a4-f5f936756ed5.PNG)

And accessing this memory in `chacha_keysetup` (chacha_private.h) got exception.
![uwp-2](https://user-images.githubusercontent.com/4927823/118372329-138f4d80-b5ec-11eb-9e0a-ecc374eff16d.PNG)
This behavior is the same with `VirtualAllocFromApp`, too.

But using `calloc` instead of `VirtualAlloc` or `VirtualAllocFromApp`, allocated memory is sane, and `chacha_keysetup` works fine.
![uwp-3](https://user-images.githubusercontent.com/4927823/118372334-18540180-b5ec-11eb-89b7-5b7c1e9f7ff2.PNG)

It is interesting that `VirtualAlloc` nor `VirtualAllocFromApp` does not work with UWP build.
I am confusing.

**Comment by feliwir** [comment]
Yes, this was exactly our observation aswell

**Comment by kinichiro** [comment]
@feliwir Could you and your colleague check #673 .
I believe this would resolve VirtualAlloc issue on UWP.

**Comment by feliwir** [comment]
@kinichiro thanks for the update, the fix looks promising. If it's okay, we'll update on the next release and check if it works for us. I looked at the PR and it looks promising though.

**Comment by feliwir** [comment]
We just tested the PR. It works for us just fine. Thanks!

**Comment by kinichiro** [comment]
@feliwir It is very good. Thanks for your report this and feedback. If you didn't post this I would not dig UWP things. Can you close this issue for  now ?
