### ISSUE TITLE
d2i_DHxparams?

### ISSUE THREAD

**Issue by davehayes** [libressl-portable/portable#773]
Referencing this: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264293

Is there a d2i_DHxparams() replacement in LibreSSL? Apologies for any naivete expressed.

**Comment by botovq** [comment]
No, we do not support the X9.42 DH parameter format. Its main purpose is
to deal with RFC 5114 groups for which there is no interest on our side.
Constructions of that ilk have been known and shown to be prone to DoS,
so we are more interested in reducing support rather than extending it.

Someone motivated could probably port the compat code for OpenSSL 1.0 in
krb5 to work with recent LibreSSL. One would need to use of OpenSSL 1.1
API to deal with various structs such as DH, X509_ALGOR, X509_PUBKEY,
ASN1_OBJECT, etc. That should all be more or less straightforward, but
admittedly a bunch of work.

https://github.com/krb5/krb5/blob/4f94e95850daa27bbf3471eae1a6a2e532910d85/src/plugins/preauth/pkinit/pkinit_crypto_openssl.c#L374-L544
