### ISSUE TITLE
no -stdname or SSL_CIPHER_standard_name

### ISSUE THREAD

**Issue by jmhodges** [libressl-portable/portable#78]
I wasn't able to find a commit history that included this. I'm willing to hear "get a new process", but being able to get the standard version of the ciphersuites name was pretty nice.

I use `openssl ciphers -stdname` to pull lists of cipher suites with their version of their names from the standards for use in [howsmyssl](https://github.com/jmhodges/howsmyssl)'s text and API (with some sed and awk, e.g. [this code](https://github.com/jmhodges/howsmyssl/blob/d273706fe53f2575d7390096a6288545de9fbf69/insecure_suites.go#L12)).

I would like to use libressl to replace this process (while recognizing I will have to keep a list of old, insecure ciphersuites that libressl drops support for), but libressl doesn't support `openssl ciphers -stdname` anymore. So, I'm unable to just move this process over. 

OpenSSL had to built with enable-ssl-trace (a.k.a. the opposite of OPENSSL_NO_SSL_TRACE) in order to enable it, which is probably how this code got ripped out.

**Comment by jmhodges** [comment]
Actually, this is so easy to redo that I'm going to close this.

**Comment by 4a6f656c** [comment]
The TLS tracing code was added after 1.0.1g, which is where LibreSSL was forked from - the cipher names are just a table:

https://github.com/openssl/openssl/blob/master/ssl/t1_trce.c#L142

While I'm not entirely against pulling some of this in to LibreSSL, IMO you are probably far better off pulling this directly from the authoritative source:

http://www.iana.org/assignments/tls-parameters/tls-parameters.xml

And given it is in XML you can even readily parse it. That said, there are cipher suites in LibreSSL that will not appear in this list, since IANA has not officially allocated cipher suite values for them.
