### ISSUE TITLE
QUIC + haproxy + LibreSSL

### ISSUE THREAD

**Issue by chipitsine** [libressl-portable/portable#784]
in haproxy only QuicTLS is considered for QUIC now.
I noticed that LibreSSL introduced some support for QUIC as well.

```
  CC      src/slz.o
  CC      src/ev_poll.o
  CC      src/ev_epoll.o
  CC      src/cpuset.o
  CC      src/ssl_sample.o
In file included from include/haproxy/listener-t.h:36,
                 from include/haproxy/connection.h:33,
                 from src/ssl_sample.c:27:
include/haproxy/xprt_quic-t.h:513:30: error: field ‘level’ has incomplete type
  513 |  enum ssl_encryption_level_t level;
      |                              ^~~~~
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:1013: src/ssl_sample.o] Error 1
```

can you consider adding `ssl_encryption_level_t` definition from QuicTLS ?

**Comment by chipitsine** [comment]
@wlallemand, fyi

**Comment by chipitsine** [comment]
I built from portable master using:

```
git clone https://github.com/libressl-portable/portable
cd portable
./autogen.sh
./configure
make dist
tar xvf libressl-3.6.0.tar.gz
cd libressl-3.6.0
./configure --prefix="${HOME}/opt"
make all install
```

**Comment by wlallemand** [comment]
@chipitsine QUIC is only available in the https://github.com/libressl-portable/openbsd repository, not the https://github.com/libressl-portable/portable one

**Comment by wlallemand** [comment]
Looks like it indeed. That could be a problem with our Makefile or includes then.

**Comment by wlallemand** [comment]
@chipitsine 

`make TARGET=linux-glibc V=1 USE_QUIC=1 SSL_INC=/opt/libressl-next/include/ SSL_LIB=/opt/libressl-next/lib/ USE_OPENSSL=1 DEFINE="-DLIBRESSL_HAS_QUIC"`

But does not compile yet, we are working on the portage. I think you can close this issue for now :)

**Comment by chipitsine** [comment]
nice, after adding `DEFINE="-DLIBRESSL_HAS_QUIC"`

```
  CC      src/xprt_quic.o
In file included from src/xprt_quic.c:53:
include/haproxy/quic_tls.h: In function ‘tls_aead’:
include/haproxy/quic_tls.h:139:10: error: implicit declaration of function ‘EVP_chacha20_poly1305’; did you mean ‘LN_chacha20_poly1305’? [-Werror=implicit-function-declaration]
  139 |   return EVP_chacha20_poly1305();
      |          ^~~~~~~~~~~~~~~~~~~~~
      |          LN_chacha20_poly1305
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
make: *** [Makefile:1013: src/xprt_quic.o] Error 1
```

**Comment by chipitsine** [comment]
ok, closing

**Comment by 4a6f656c** [comment]
@chipitsine @wlallemand just to follow up on this, our support for QUIC and the corresponding APIs is usable, but still needs some work. As such, we've not yet exposed it, but it should be available in our next development release (or by defining `LIBRESSL_HAS_QUIC` as you've discovered). Additionally, `EVP_chacha20_poly1305()` will also be available in our next development release (although I'd strongly recommend making use of our `EVP_AEAD` interface instead, if you're willing to carry conditionals for LibreSSL). This can also be exposed ahead of time if you define `LIBRESSL_NEXT_API` if you wish to do so.

Please let us know if you encounter any issues or we can assist further.

**Comment by wlallemand** [comment]
@4a6f656c Thanks for your feedback. I managed to compile libressl-portable with CFLAGS=-DLIBRESSL_HAS_QUIC and did the same with HAProxy. It looks like the symbols are not exposed yet for the API so I did everything with the static library. Everything is compiling and linking with the https://github.com/haproxy/haproxy/tree/20220901-libressl3_6_0 branch, but not working yet :-)

Indeed I fall on the EVP_chacha20_poly1305() problem which I disabled for now, I'll take a look at the EAVP_AEAD API once I have the other parts working. The SSL_CTX_set_client_hello_cb() was also disabled since it's not available in libreSSL, we massively uses it instead of the servername callback.

**Comment by wlallemand** [comment]
@4a6f656c We successfully ported haproxy to the libreSSL implementation, it's available in the master branch. The only change of behavior we had was with the `set_encryption_secrets` callback which is called with a NULL write_secret or read_secret, which is not the case with quicTLS. We also had to support the servername callback which was not supported anymore since we are using `SSL_CTX_set_client_hello_cb()` with OpenSSL, so there will be some unsupported features for now.
