### ISSUE TITLE
 regression in 3.6.0 (cert expiration check)

### ISSUE THREAD

**Issue by chipitsine** [libressl-portable/portable#792]
in haproxy we run auto tests using both OpenSSL and LibreSSL.

when I use LibreSSL-3.6.0, some autotests fail, looks like regression.

repro steps:

```
git clone https://github.com/haproxy/haproxy
LIBRESSL_VERSION=3.6.0 ./scripts/build-ssl.sh
make CC=gcc TARGET=linux-glibc USE_OPENSSL=1 ADDLIB="-Wl,-rpath,${HOME}/opt/lib" SSL_LIB=${HOME}/opt/lib SSL_INC=${HOME}/opt/include
./scripts/build-vtest.sh
make reg-tests VTEST_PROGRAM=../vtest/vtest -- --debug reg-tests/ssl/ssl_default_server.vtc
make reg-tests VTEST_PROGRAM=../vtest/vtest -- --debug reg-tests/ssl/set_ssl_server_cert.vtc
make reg-tests VTEST_PROGRAM=../vtest/vtest -- --debug reg-tests/ssl/ssl_client_auth.vtc
```

**Comment by chipitsine** [comment]
in theory I can setup weekly build/test against master tp catch such things before release

**Comment by 4a6f656c** [comment]
Thanks for the report - our own regress should have caught this, but failed to do so due to the way it was wired up (it has now been adjusted to ensure that it does in the future). The issue itself is fixed via https://github.com/openbsd/src/commit/4f94258c65a918ee3d8670e93916d15bf879e6ec (and will be in a future 3.6.1 release).

**Comment by chipitsine** [comment]
thank you very much
