### ISSUE TITLE
autogen.sh on portable 2.2.0 prompts for patch ?

### ISSUE THREAD

**Issue by centminmod** [libressl-portable/portable#99]
I compile LibreSSL 2.2.0 for Nginx statically and all working fine until now. Seems on autogen.sh run you now prompting for a patch which messes up scripted unattended installs for me. What is the proper answer for this prompt ? and automating it ?

    pulling upstream openbsd source
    Already on 'master'
    Current branch master is up to date.
    libcrypto version 33:0:0
    libssl version 32:0:0
    libtls version 3:1:0
    patching file include/tls.h
    Reversed (or previously applied) patch detected!  Assume -R? [n]

after autogen.sh run

    grep -R 'patch -p0' /svr-setup/portable-2.2.0
    /svr-setup/portable-2.2.0/update.sh:patch -p0 < patches/tls.h.patch
    /svr-setup/portable-2.2.0/update.sh:patch -p0 < patches/openssl.c.patch

**Comment by busterb** [comment]
That patch is already removed, so adding your workaround should not be needed.

I think the problem is, if you are checking out the tag for 2.2.0 portable from git, you still the latest openbsd source. Rather than building 2.2.0 from github source using a tag, please use the release tarball for 2.2.0 instead: http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.2.0.tar.gz . Is there some reason why you need to use the git tree to get an already-released version?

We actually need a way to check out a specific version of the openbsd source when on a tag, but still allow it to float to latest for development. I've avoided this up to now due to previously-unstable git hashes on CVS import from openbsd (adding a new directory would rewrite everything). This is also why we did not use git submodules either. But, there may be a way to add tags to the openbsd source after the fact now that things have slowed down a bit with regard to repository motion.

**Comment by busterb** [comment]
Patch was removed in b67c9460bafb71e8f294c6469c15ccd20e65c4c4

**Comment by centminmod** [comment]
thanks @busterb I assumed git releases would be the most frequently updated and available so can get the latest before the site updated version :) But yeah probably better to use http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.2.0.tar.gz
